{
  "fa155d7653b9e0c845b6e9a3ce3a99c3" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "e32d70305aeb3bb9",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/e32d70305aeb3bb9",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='frontend.niffler.dc', port=80): Max retries exceeded with url: /authorized?code=IKxl6aT1vru-4ckeYgtZCJ23atz7r7TJ03KuWA9PU5BYfuppu01oiq3k8k8c50ZEO3d7eRAvCKdaoi33ygG9LSAZIzJxRqB_VoJ-9CCOxXoCUsDdXcaHTSWz6G59QypH (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f96a8c08190>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1750752664787,
        "stop" : 1750752664787,
        "duration" : 0
      }
    }, {
      "uid" : "77236e43b15d53bf",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/77236e43b15d53bf",
      "status" : "passed",
      "time" : {
        "start" : 1750735603475,
        "stop" : 1750735603544,
        "duration" : 69
      }
    } ]
  },
  "6069d10c7fd57600599599067a64d650" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "a7c2b2d691b243cc",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/a7c2b2d691b243cc",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='frontend.niffler.dc', port=80): Max retries exceeded with url: /authorized?code=4oNXVbZDPy3rkhy0KIsRurQDzI9saIsESvNqGiQ7isna8NpKjuZQKgn49RZ8gHMov0eJfA1PWPeYM9q9BMBxi1WiVeivh4gjZYdZ209upA9IoDM6k7YbEiYEiNrQ3Mdy (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f22a8d34190>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1750752666503,
        "stop" : 1750752666503,
        "duration" : 0
      }
    }, {
      "uid" : "98066e10681747d",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/98066e10681747d",
      "status" : "passed",
      "time" : {
        "start" : 1750735603850,
        "stop" : 1750735603874,
        "duration" : 24
      }
    } ]
  },
  "05b8f69e3842d9adf9c4c4e27723b1ba" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "f0841d328b402ea2",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/f0841d328b402ea2",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='frontend.niffler.dc', port=80): Max retries exceeded with url: /authorized?code=3AotFZI33KoDWPLmg19wOsxNRQPPVu_ebHst4OPCctlx4XkcIga6qLyNi6OTYLAT7B793yqxpJ8fEujXLue3QH2Qh4h3S1NWB3hzDveyJKCKLDXwRtbWKHf0SLIKof1g (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe8db9f8a50>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1750752654182,
        "stop" : 1750752654182,
        "duration" : 0
      }
    }, {
      "uid" : "b66c80d97a3abca5",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/b66c80d97a3abca5",
      "status" : "passed",
      "time" : {
        "start" : 1750735579914,
        "stop" : 1750735580816,
        "duration" : 902
      }
    } ]
  },
  "58e83f624be3d7deb9304954eee10fdf" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "1a3d118ca6679f1e",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/1a3d118ca6679f1e",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='frontend.niffler.dc', port=80): Max retries exceeded with url: /authorized?code=3AotFZI33KoDWPLmg19wOsxNRQPPVu_ebHst4OPCctlx4XkcIga6qLyNi6OTYLAT7B793yqxpJ8fEujXLue3QH2Qh4h3S1NWB3hzDveyJKCKLDXwRtbWKHf0SLIKof1g (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe8db9f8a50>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1750752638406,
        "stop" : 1750752638406,
        "duration" : 0
      }
    }, {
      "uid" : "cd1fd3c396fb3772",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/cd1fd3c396fb3772",
      "status" : "passed",
      "time" : {
        "start" : 1750735564592,
        "stop" : 1750735566215,
        "duration" : 1623
      }
    } ]
  },
  "407477b13f4104a3ae7c709240a2d9e5" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "ce0eeda9d3cf9e43",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/ce0eeda9d3cf9e43",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='frontend.niffler.dc', port=80): Max retries exceeded with url: /authorized?code=4oNXVbZDPy3rkhy0KIsRurQDzI9saIsESvNqGiQ7isna8NpKjuZQKgn49RZ8gHMov0eJfA1PWPeYM9q9BMBxi1WiVeivh4gjZYdZ209upA9IoDM6k7YbEiYEiNrQ3Mdy (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f22a8d34190>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1750752666032,
        "stop" : 1750752666032,
        "duration" : 0
      }
    }, {
      "uid" : "de2570bd8e18e410",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/de2570bd8e18e410",
      "status" : "passed",
      "time" : {
        "start" : 1750735603811,
        "stop" : 1750735603830,
        "duration" : 19
      }
    } ]
  },
  "a060b4b053e8f1858c9d1cd8fb01bf2d" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "df463e6c3e643fd4",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/df463e6c3e643fd4",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='frontend.niffler.dc', port=80): Max retries exceeded with url: /authorized?code=3AotFZI33KoDWPLmg19wOsxNRQPPVu_ebHst4OPCctlx4XkcIga6qLyNi6OTYLAT7B793yqxpJ8fEujXLue3QH2Qh4h3S1NWB3hzDveyJKCKLDXwRtbWKHf0SLIKof1g (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe8db9f8a50>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1750752653770,
        "stop" : 1750752653770,
        "duration" : 0
      }
    }, {
      "uid" : "ac961bd230a7053",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/ac961bd230a7053",
      "status" : "passed",
      "time" : {
        "start" : 1750735576976,
        "stop" : 1750735577012,
        "duration" : 36
      }
    } ]
  },
  "87a01575c018288b90a75a76ac7d6e03" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 0,
      "skipped" : 0,
      "passed" : 2,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "698d205d30ad1023",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/698d205d30ad1023",
      "status" : "passed",
      "time" : {
        "start" : 1750752666222,
        "stop" : 1750752667145,
        "duration" : 923
      }
    }, {
      "uid" : "706798caf67e6c69",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/706798caf67e6c69",
      "status" : "passed",
      "time" : {
        "start" : 1750735608480,
        "stop" : 1750735608960,
        "duration" : 480
      }
    } ]
  },
  "592b6b4e55603ad13e412cb367842e2b" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "1748f1b46ff60386",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/1748f1b46ff60386",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='frontend.niffler.dc', port=80): Max retries exceeded with url: /authorized?code=3AotFZI33KoDWPLmg19wOsxNRQPPVu_ebHst4OPCctlx4XkcIga6qLyNi6OTYLAT7B793yqxpJ8fEujXLue3QH2Qh4h3S1NWB3hzDveyJKCKLDXwRtbWKHf0SLIKof1g (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe8db9f8a50>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1750752654505,
        "stop" : 1750752654505,
        "duration" : 0
      }
    }, {
      "uid" : "dbfa8d3570a290f1",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/dbfa8d3570a290f1",
      "status" : "passed",
      "time" : {
        "start" : 1750735583721,
        "stop" : 1750735584502,
        "duration" : 781
      }
    } ]
  },
  "28b0cc787e19b8a2e5d116874aa3afad" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "bacecba924cb7a14",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/bacecba924cb7a14",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8089): Max retries exceeded with url: /ws (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f96a8b15ae0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1750752669796,
        "stop" : 1750752670049,
        "duration" : 253
      }
    }, {
      "uid" : "72a2b050e5b488e",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/72a2b050e5b488e",
      "status" : "passed",
      "time" : {
        "start" : 1750735605475,
        "stop" : 1750735605962,
        "duration" : 487
      }
    } ]
  },
  "d46086a8337959dfa1321c6a04313b33" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "9ddf0f606959f5de",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/9ddf0f606959f5de",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='frontend.niffler.dc', port=80): Max retries exceeded with url: /authorized?code=IKxl6aT1vru-4ckeYgtZCJ23atz7r7TJ03KuWA9PU5BYfuppu01oiq3k8k8c50ZEO3d7eRAvCKdaoi33ygG9LSAZIzJxRqB_VoJ-9CCOxXoCUsDdXcaHTSWz6G59QypH (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f96a8c08190>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1750752664355,
        "stop" : 1750752664355,
        "duration" : 0
      }
    }, {
      "uid" : "d01765cd57bcc7d5",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/d01765cd57bcc7d5",
      "status" : "passed",
      "time" : {
        "start" : 1750735603415,
        "stop" : 1750735603438,
        "duration" : 23
      }
    } ]
  },
  "8acd6b4b25069584c97d5a73c1515706" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "9d99433d6af2236b",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/9d99433d6af2236b",
      "status" : "broken",
      "statusDetails" : "sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation \"user\" does not exist\nLINE 2: FROM \"user\" \n             ^\n\n[SQL: SELECT \"user\".id, \"user\".username, \"user\".currency, \"user\".firstname, \"user\".surname, \"user\".photo, \"user\".photo_small, \"user\".full_name \nFROM \"user\" \nWHERE \"user\".username = %(username_1)s]\n[parameters: {'username_1': 'Richard Jones'}]\n(Background on this error at: https://sqlalche.me/e/20/f405)",
      "time" : {
        "start" : 1750752668339,
        "stop" : 1750752668658,
        "duration" : 319
      }
    }, {
      "uid" : "e869002df2391b4b",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/e869002df2391b4b",
      "status" : "passed",
      "time" : {
        "start" : 1750735604115,
        "stop" : 1750735604643,
        "duration" : 528
      }
    } ]
  },
  "00f8708f1b4b17abf3270fc6ddb19c2e" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "b1e3bc5927b3f6db",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/b1e3bc5927b3f6db",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=137.0.7151.103)\nStacktrace:\n#0 0x560f950b1c9a <unknown>\n#1 0x560f94b576e0 <unknown>\n#2 0x560f94b4e7e7 <unknown>\n#3 0x560f94b3f699 <unknown>\n#4 0x560f94b413e0 <unknown>\n#5 0x560f94b3fa3d <unknown>\n#6 0x560f94b3f3af <unknown>\n#7 0x560f94b3f085 <unknown>\n#8 0x560f94b3ceee <unknown>\n#9 0x560f94b3d6ca <unknown>\n#10 0x560f94b5ac09 <unknown>\n#11 0x560f94bf5ed5 <unknown>\n#12 0x560f94bcee32 <unknown>\n#13 0x560f94bf52cc <unknown>\n#14 0x560f94bcec03 <unknown>\n#15 0x560f94b9b47b <unknown>\n#16 0x560f94b9c0e1 <unknown>\n#17 0x560f9507644b <unknown>\n#18 0x560f9507a37f <unknown>\n#19 0x560f9505df89 <unknown>\n#20 0x560f9507af18 <unknown>\n#21 0x560f950426df <unknown>\n#22 0x560f9509f308 <unknown>\n#23 0x560f9509f4e6 <unknown>\n#24 0x560f950b0b76 <unknown>\n#25 0x7f009da9caa4 <unknown>\n#26 0x7f009db29c3c <unknown>",
      "time" : {
        "start" : 1750752653204,
        "stop" : 1750752653204,
        "duration" : 0
      }
    }, {
      "uid" : "21ff90d26378b864",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/21ff90d26378b864",
      "status" : "passed",
      "time" : {
        "start" : 1750735567845,
        "stop" : 1750735568699,
        "duration" : 854
      }
    } ]
  },
  "759c09bff7ce6e69a155fd02f8155bd6" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "1113bd0e8fb46661",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/1113bd0e8fb46661",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='frontend.niffler.dc', port=80): Max retries exceeded with url: /authorized?code=4oNXVbZDPy3rkhy0KIsRurQDzI9saIsESvNqGiQ7isna8NpKjuZQKgn49RZ8gHMov0eJfA1PWPeYM9q9BMBxi1WiVeivh4gjZYdZ209upA9IoDM6k7YbEiYEiNrQ3Mdy (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f22a8d34190>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1750752664771,
        "stop" : 1750752664771,
        "duration" : 0
      }
    }, {
      "uid" : "e7d3424b711fdc23",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/e7d3424b711fdc23",
      "status" : "passed",
      "time" : {
        "start" : 1750735603306,
        "stop" : 1750735603322,
        "duration" : 16
      }
    } ]
  },
  "7fe3a328b5bbd8271f4adad729d97981" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 0,
      "skipped" : 0,
      "passed" : 2,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "ab456c99e4e94c36",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/ab456c99e4e94c36",
      "status" : "passed",
      "time" : {
        "start" : 1750752667662,
        "stop" : 1750752668893,
        "duration" : 1231
      }
    }, {
      "uid" : "26629429272ef677",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/26629429272ef677",
      "status" : "passed",
      "time" : {
        "start" : 1750735605921,
        "stop" : 1750735607060,
        "duration" : 1139
      }
    } ]
  },
  "99ca71783eb0c0fd5679b38e2529b40f" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "45785ffff2028d64",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/45785ffff2028d64",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=137.0.7151.103)\nStacktrace:\n#0 0x560f950b1c9a <unknown>\n#1 0x560f94b576e0 <unknown>\n#2 0x560f94b4e7e7 <unknown>\n#3 0x560f94b3f699 <unknown>\n#4 0x560f94b413e0 <unknown>\n#5 0x560f94b3fa3d <unknown>\n#6 0x560f94b3f3af <unknown>\n#7 0x560f94b3f085 <unknown>\n#8 0x560f94b3ceee <unknown>\n#9 0x560f94b3d6ca <unknown>\n#10 0x560f94b5ac09 <unknown>\n#11 0x560f94bf5ed5 <unknown>\n#12 0x560f94bcee32 <unknown>\n#13 0x560f94bf52cc <unknown>\n#14 0x560f94bcec03 <unknown>\n#15 0x560f94b9b47b <unknown>\n#16 0x560f94b9c0e1 <unknown>\n#17 0x560f9507644b <unknown>\n#18 0x560f9507a37f <unknown>\n#19 0x560f9505df89 <unknown>\n#20 0x560f9507af18 <unknown>\n#21 0x560f950426df <unknown>\n#22 0x560f9509f308 <unknown>\n#23 0x560f9509f4e6 <unknown>\n#24 0x560f950b0b76 <unknown>\n#25 0x7f009da9caa4 <unknown>\n#26 0x7f009db29c3c <unknown>",
      "time" : {
        "start" : 1750752653267,
        "stop" : 1750752653267,
        "duration" : 0
      }
    }, {
      "uid" : "c351b38e0e15907a",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/c351b38e0e15907a",
      "status" : "passed",
      "time" : {
        "start" : 1750735570444,
        "stop" : 1750735571732,
        "duration" : 1288
      }
    } ]
  },
  "d44bbf7a21a7c4f73247e7044f459a7e" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "db7eb26af598aab2",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/db7eb26af598aab2",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=137.0.7151.103)\nStacktrace:\n#0 0x560f950b1c9a <unknown>\n#1 0x560f94b576e0 <unknown>\n#2 0x560f94b4e7e7 <unknown>\n#3 0x560f94b3f699 <unknown>\n#4 0x560f94b413e0 <unknown>\n#5 0x560f94b3fa3d <unknown>\n#6 0x560f94b3f3af <unknown>\n#7 0x560f94b3f085 <unknown>\n#8 0x560f94b3ceee <unknown>\n#9 0x560f94b3d6ca <unknown>\n#10 0x560f94b5ac09 <unknown>\n#11 0x560f94bf5ed5 <unknown>\n#12 0x560f94bcee32 <unknown>\n#13 0x560f94bf52cc <unknown>\n#14 0x560f94bcec03 <unknown>\n#15 0x560f94b9b47b <unknown>\n#16 0x560f94b9c0e1 <unknown>\n#17 0x560f9507644b <unknown>\n#18 0x560f9507a37f <unknown>\n#19 0x560f9505df89 <unknown>\n#20 0x560f9507af18 <unknown>\n#21 0x560f950426df <unknown>\n#22 0x560f9509f308 <unknown>\n#23 0x560f9509f4e6 <unknown>\n#24 0x560f950b0b76 <unknown>\n#25 0x7f009da9caa4 <unknown>\n#26 0x7f009db29c3c <unknown>",
      "time" : {
        "start" : 1750752653300,
        "stop" : 1750752653300,
        "duration" : 0
      }
    }, {
      "uid" : "cc09f2778d7e765d",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/cc09f2778d7e765d",
      "status" : "passed",
      "time" : {
        "start" : 1750735571734,
        "stop" : 1750735573460,
        "duration" : 1726
      }
    } ]
  },
  "751859e68dae90ea11b5030340fbbd9d" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "e82d0784544a09e",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/e82d0784544a09e",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=137.0.7151.103)\nStacktrace:\n#0 0x560f950b1c9a <unknown>\n#1 0x560f94b576e0 <unknown>\n#2 0x560f94b4e7e7 <unknown>\n#3 0x560f94b3f699 <unknown>\n#4 0x560f94b413e0 <unknown>\n#5 0x560f94b3fa3d <unknown>\n#6 0x560f94b3f3af <unknown>\n#7 0x560f94b3f085 <unknown>\n#8 0x560f94b3ceee <unknown>\n#9 0x560f94b3d6ca <unknown>\n#10 0x560f94b5ac09 <unknown>\n#11 0x560f94bf5ed5 <unknown>\n#12 0x560f94bcee32 <unknown>\n#13 0x560f94bf52cc <unknown>\n#14 0x560f94bcec03 <unknown>\n#15 0x560f94b9b47b <unknown>\n#16 0x560f94b9c0e1 <unknown>\n#17 0x560f9507644b <unknown>\n#18 0x560f9507a37f <unknown>\n#19 0x560f9505df89 <unknown>\n#20 0x560f9507af18 <unknown>\n#21 0x560f950426df <unknown>\n#22 0x560f9509f308 <unknown>\n#23 0x560f9509f4e6 <unknown>\n#24 0x560f950b0b76 <unknown>\n#25 0x7f009da9caa4 <unknown>\n#26 0x7f009db29c3c <unknown>",
      "time" : {
        "start" : 1750752654445,
        "stop" : 1750752654445,
        "duration" : 0
      }
    }, {
      "uid" : "671859834697ab8a",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/671859834697ab8a",
      "status" : "passed",
      "time" : {
        "start" : 1750735581776,
        "stop" : 1750735582749,
        "duration" : 973
      }
    } ]
  },
  "3c2e21788ede0f987203708006cd63af" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "c4dffbc9a2e4cdd",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/c4dffbc9a2e4cdd",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8089): Max retries exceeded with url: /ws (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f002d9bf4d0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1750752666086,
        "stop" : 1750752666098,
        "duration" : 12
      }
    }, {
      "uid" : "68a194cceba65a3",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/68a194cceba65a3",
      "status" : "passed",
      "time" : {
        "start" : 1750735603936,
        "stop" : 1750735603962,
        "duration" : 26
      }
    } ]
  },
  "866c918210b2364391677dc02a92a7ae" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "b44c5d3aeb3f39e5",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/b44c5d3aeb3f39e5",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='frontend.niffler.dc', port=80): Max retries exceeded with url: /authorized?code=IKxl6aT1vru-4ckeYgtZCJ23atz7r7TJ03KuWA9PU5BYfuppu01oiq3k8k8c50ZEO3d7eRAvCKdaoi33ygG9LSAZIzJxRqB_VoJ-9CCOxXoCUsDdXcaHTSWz6G59QypH (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f96a8c08190>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1750752663404,
        "stop" : 1750752663404,
        "duration" : 0
      }
    }, {
      "uid" : "7c342a485ad8c0bb",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/7c342a485ad8c0bb",
      "status" : "passed",
      "time" : {
        "start" : 1750735603381,
        "stop" : 1750735603410,
        "duration" : 29
      }
    } ]
  },
  "01367fb538fe8768c0bc2c684f545bd1" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "7e600c7103514f6",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/7e600c7103514f6",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='frontend.niffler.dc', port=80): Max retries exceeded with url: /authorized?code=3AotFZI33KoDWPLmg19wOsxNRQPPVu_ebHst4OPCctlx4XkcIga6qLyNi6OTYLAT7B793yqxpJ8fEujXLue3QH2Qh4h3S1NWB3hzDveyJKCKLDXwRtbWKHf0SLIKof1g (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe8db9f8a50>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1750752655700,
        "stop" : 1750752655700,
        "duration" : 0
      }
    }, {
      "uid" : "3a969960841dd57d",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/3a969960841dd57d",
      "status" : "passed",
      "time" : {
        "start" : 1750735594709,
        "stop" : 1750735595384,
        "duration" : 675
      }
    } ]
  },
  "512542516cc1429f300b8573764ecdb0" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "95627e69b8c45cb8",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/95627e69b8c45cb8",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=137.0.7151.103)\nStacktrace:\n#0 0x560f950b1c9a <unknown>\n#1 0x560f94b576e0 <unknown>\n#2 0x560f94b4e7e7 <unknown>\n#3 0x560f94b3f699 <unknown>\n#4 0x560f94b413e0 <unknown>\n#5 0x560f94b3fa3d <unknown>\n#6 0x560f94b3f3af <unknown>\n#7 0x560f94b3f085 <unknown>\n#8 0x560f94b3ceee <unknown>\n#9 0x560f94b3d6ca <unknown>\n#10 0x560f94b5ac09 <unknown>\n#11 0x560f94bf5ed5 <unknown>\n#12 0x560f94bcee32 <unknown>\n#13 0x560f94bf52cc <unknown>\n#14 0x560f94bcec03 <unknown>\n#15 0x560f94b9b47b <unknown>\n#16 0x560f94b9c0e1 <unknown>\n#17 0x560f9507644b <unknown>\n#18 0x560f9507a37f <unknown>\n#19 0x560f9505df89 <unknown>\n#20 0x560f9507af18 <unknown>\n#21 0x560f950426df <unknown>\n#22 0x560f9509f308 <unknown>\n#23 0x560f9509f4e6 <unknown>\n#24 0x560f950b0b76 <unknown>\n#25 0x7f009da9caa4 <unknown>\n#26 0x7f009db29c3c <unknown>",
      "time" : {
        "start" : 1750752653235,
        "stop" : 1750752653235,
        "duration" : 0
      }
    }, {
      "uid" : "f4dfe220a521da07",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/f4dfe220a521da07",
      "status" : "passed",
      "time" : {
        "start" : 1750735568700,
        "stop" : 1750735570442,
        "duration" : 1742
      }
    } ]
  },
  "4e614238fb254857df90d7fce14a17a1" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 2,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "2c4461dcefa46905",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/2c4461dcefa46905",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='frontend.niffler.dc', port=80): Max retries exceeded with url: /authorized?code=f_7ZaLs_ugxv2_KBSVnEK0-o0EuhzJAiVxQr6zvsl2rNvJFWrNrcXo1awgLKtndla6m4Cphq23tEaFRXEQPN39vOjXwc5JB7_psbZfX0ckkXm6vkvTYRGtsHgk_IpySZ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff2a82cc190>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1750752663404,
        "stop" : 1750752663404,
        "duration" : 0
      }
    }, {
      "uid" : "44e9d9ca10838965",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/44e9d9ca10838965",
      "status" : "broken",
      "statusDetails" : "sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) update or delete on table \"category\" violates foreign key constraint \"fk_spend_category\" on table \"spend\"\nDETAIL:  Key (id)=(7a958c45-f242-4652-93b6-36e6c5403f6d) is still referenced from table \"spend\".\n\n[SQL: DELETE FROM category WHERE category.id = %(id)s]\n[parameters: {'id': UUID('7a958c45-f242-4652-93b6-36e6c5403f6d')}]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)",
      "time" : {
        "start" : 1750735602144,
        "stop" : 1750735602144,
        "duration" : 0
      }
    } ]
  },
  "d94ce57622e0c972fcd69976f76b33e7" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 0,
      "skipped" : 0,
      "passed" : 2,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "2dec9bb89a661971",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/2dec9bb89a661971",
      "status" : "passed",
      "time" : {
        "start" : 1750752656182,
        "stop" : 1750752656460,
        "duration" : 278
      }
    }, {
      "uid" : "22e9286af1f5e54c",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/22e9286af1f5e54c",
      "status" : "passed",
      "time" : {
        "start" : 1750735595604,
        "stop" : 1750735595777,
        "duration" : 173
      }
    } ]
  },
  "3c82ff2e505c273710292b0ef5e1a978" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "9a1c976233a1e356",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/9a1c976233a1e356",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8089): Max retries exceeded with url: /ws (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f002d941cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1750752666513,
        "stop" : 1750752666519,
        "duration" : 6
      }
    }, {
      "uid" : "8c9488cd512cf4bb",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/8c9488cd512cf4bb",
      "status" : "passed",
      "time" : {
        "start" : 1750735603966,
        "stop" : 1750735603978,
        "duration" : 12
      }
    } ]
  },
  "7bd12753fff2701f4e63fd7bfc86668a" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "2e4fb80b55bfc3d9",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/2e4fb80b55bfc3d9",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=137.0.7151.103)\nStacktrace:\n#0 0x555c80270c9a <unknown>\n#1 0x555c7fd166e0 <unknown>\n#2 0x555c7fd0d7e7 <unknown>\n#3 0x555c7fcfe699 <unknown>\n#4 0x555c7fd003e0 <unknown>\n#5 0x555c7fcfea3d <unknown>\n#6 0x555c7fcfe3af <unknown>\n#7 0x555c7fcfe085 <unknown>\n#8 0x555c7fcfbeee <unknown>\n#9 0x555c7fcfc6ca <unknown>\n#10 0x555c7fd19c09 <unknown>\n#11 0x555c7fdb4ed5 <unknown>\n#12 0x555c7fd8de32 <unknown>\n#13 0x555c7fdb42cc <unknown>\n#14 0x555c7fd8dc03 <unknown>\n#15 0x555c7fd5a47b <unknown>\n#16 0x555c7fd5b0e1 <unknown>\n#17 0x555c8023544b <unknown>\n#18 0x555c8023937f <unknown>\n#19 0x555c8021cf89 <unknown>\n#20 0x555c80239f18 <unknown>\n#21 0x555c802016df <unknown>\n#22 0x555c8025e308 <unknown>\n#23 0x555c8025e4e6 <unknown>\n#24 0x555c8026fb76 <unknown>\n#25 0x7feac889caa4 <unknown>\n#26 0x7feac8929c3c <unknown>",
      "time" : {
        "start" : 1750752668266,
        "stop" : 1750752668571,
        "duration" : 305
      }
    }, {
      "uid" : "7001c81bedb8d641",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/7001c81bedb8d641",
      "status" : "passed",
      "time" : {
        "start" : 1750735606884,
        "stop" : 1750735607990,
        "duration" : 1106
      }
    } ]
  },
  "fa289b81b102a512afc316ad3b2441ca" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "46ad7fef586af5a7",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/46ad7fef586af5a7",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='frontend.niffler.dc', port=80): Max retries exceeded with url: /authorized?code=3AotFZI33KoDWPLmg19wOsxNRQPPVu_ebHst4OPCctlx4XkcIga6qLyNi6OTYLAT7B793yqxpJ8fEujXLue3QH2Qh4h3S1NWB3hzDveyJKCKLDXwRtbWKHf0SLIKof1g (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe8db9f8a50>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1750752655965,
        "stop" : 1750752655965,
        "duration" : 0
      }
    }, {
      "uid" : "d982b89c92fbe752",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/d982b89c92fbe752",
      "status" : "passed",
      "time" : {
        "start" : 1750735595482,
        "stop" : 1750735595499,
        "duration" : 17
      }
    } ]
  },
  "020e13f90194e376bcf5825bce02bdfe" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "694c80d7451b3a00",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/694c80d7451b3a00",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='frontend.niffler.dc', port=80): Max retries exceeded with url: /authorized?code=3AotFZI33KoDWPLmg19wOsxNRQPPVu_ebHst4OPCctlx4XkcIga6qLyNi6OTYLAT7B793yqxpJ8fEujXLue3QH2Qh4h3S1NWB3hzDveyJKCKLDXwRtbWKHf0SLIKof1g (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe8db9f8a50>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1750752653578,
        "stop" : 1750752653578,
        "duration" : 0
      }
    }, {
      "uid" : "e48c7b674d046e83",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/e48c7b674d046e83",
      "status" : "passed",
      "time" : {
        "start" : 1750735576823,
        "stop" : 1750735576843,
        "duration" : 20
      }
    } ]
  },
  "15afa45c594f4a42832d76ef6ff26b0d" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "b43663e03dc09cf0",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/b43663e03dc09cf0",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=137.0.7151.103)\nStacktrace:\n#0 0x560f950b1c9a <unknown>\n#1 0x560f94b576e0 <unknown>\n#2 0x560f94b4e7e7 <unknown>\n#3 0x560f94b3f699 <unknown>\n#4 0x560f94b413e0 <unknown>\n#5 0x560f94b3fa3d <unknown>\n#6 0x560f94b3f3af <unknown>\n#7 0x560f94b3f085 <unknown>\n#8 0x560f94b3ceee <unknown>\n#9 0x560f94b3d6ca <unknown>\n#10 0x560f94b5ac09 <unknown>\n#11 0x560f94bf5ed5 <unknown>\n#12 0x560f94bcee32 <unknown>\n#13 0x560f94bf52cc <unknown>\n#14 0x560f94bcec03 <unknown>\n#15 0x560f94b9b47b <unknown>\n#16 0x560f94b9c0e1 <unknown>\n#17 0x560f9507644b <unknown>\n#18 0x560f9507a37f <unknown>\n#19 0x560f9505df89 <unknown>\n#20 0x560f9507af18 <unknown>\n#21 0x560f950426df <unknown>\n#22 0x560f9509f308 <unknown>\n#23 0x560f9509f4e6 <unknown>\n#24 0x560f950b0b76 <unknown>\n#25 0x7f009da9caa4 <unknown>\n#26 0x7f009db29c3c <unknown>",
      "time" : {
        "start" : 1750752653173,
        "stop" : 1750752653173,
        "duration" : 0
      }
    }, {
      "uid" : "15e9df332821784f",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/15e9df332821784f",
      "status" : "passed",
      "time" : {
        "start" : 1750735566991,
        "stop" : 1750735567843,
        "duration" : 852
      }
    } ]
  },
  "967c4ac0a7887dc9053c9e349c16e83c" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "addf5216bcda03e6",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/addf5216bcda03e6",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='frontend.niffler.dc', port=80): Max retries exceeded with url: /authorized?code=3AotFZI33KoDWPLmg19wOsxNRQPPVu_ebHst4OPCctlx4XkcIga6qLyNi6OTYLAT7B793yqxpJ8fEujXLue3QH2Qh4h3S1NWB3hzDveyJKCKLDXwRtbWKHf0SLIKof1g (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe8db9f8a50>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1750752655570,
        "stop" : 1750752655570,
        "duration" : 0
      }
    }, {
      "uid" : "cb4b0e15174fc595",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/cb4b0e15174fc595",
      "status" : "passed",
      "time" : {
        "start" : 1750735592600,
        "stop" : 1750735594650,
        "duration" : 2050
      }
    } ]
  },
  "a7fff6128b26ee31e8e9d6ae551bf762" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "2a9a1d6423a3007c",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/2a9a1d6423a3007c",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='frontend.niffler.dc', port=80): Max retries exceeded with url: /authorized?code=3AotFZI33KoDWPLmg19wOsxNRQPPVu_ebHst4OPCctlx4XkcIga6qLyNi6OTYLAT7B793yqxpJ8fEujXLue3QH2Qh4h3S1NWB3hzDveyJKCKLDXwRtbWKHf0SLIKof1g (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe8db9f8a50>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1750752654051,
        "stop" : 1750752654051,
        "duration" : 0
      }
    }, {
      "uid" : "c740d729c584f762",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/c740d729c584f762",
      "status" : "passed",
      "time" : {
        "start" : 1750735578413,
        "stop" : 1750735579911,
        "duration" : 1498
      }
    } ]
  },
  "7e3c089ea847b9daba9c17bc6f79394a" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "8e8e0ec8aaf18288",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/8e8e0ec8aaf18288",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='frontend.niffler.dc', port=80): Max retries exceeded with url: /authorized?code=3AotFZI33KoDWPLmg19wOsxNRQPPVu_ebHst4OPCctlx4XkcIga6qLyNi6OTYLAT7B793yqxpJ8fEujXLue3QH2Qh4h3S1NWB3hzDveyJKCKLDXwRtbWKHf0SLIKof1g (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe8db9f8a50>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1750752653905,
        "stop" : 1750752653905,
        "duration" : 0
      }
    }, {
      "uid" : "e8bca75dc79154c8",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/e8bca75dc79154c8",
      "status" : "passed",
      "time" : {
        "start" : 1750735577476,
        "stop" : 1750735578411,
        "duration" : 935
      }
    } ]
  },
  "e24ccb13b7bdf0c1c79fb281155ee83f" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "ffdaed841be5b554",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/ffdaed841be5b554",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='frontend.niffler.dc', port=80): Max retries exceeded with url: /authorized?code=IKxl6aT1vru-4ckeYgtZCJ23atz7r7TJ03KuWA9PU5BYfuppu01oiq3k8k8c50ZEO3d7eRAvCKdaoi33ygG9LSAZIzJxRqB_VoJ-9CCOxXoCUsDdXcaHTSWz6G59QypH (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f96a8c08190>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1750752665634,
        "stop" : 1750752665634,
        "duration" : 0
      }
    }, {
      "uid" : "b0de46d9f1d22987",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/b0de46d9f1d22987",
      "status" : "passed",
      "time" : {
        "start" : 1750735603903,
        "stop" : 1750735603969,
        "duration" : 66
      }
    } ]
  },
  "8ced8d8e482767490164e8f48a2ed1f6" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "30be149c995d79b8",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/30be149c995d79b8",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='frontend.niffler.dc', port=80): Max retries exceeded with url: /authorized?code=3AotFZI33KoDWPLmg19wOsxNRQPPVu_ebHst4OPCctlx4XkcIga6qLyNi6OTYLAT7B793yqxpJ8fEujXLue3QH2Qh4h3S1NWB3hzDveyJKCKLDXwRtbWKHf0SLIKof1g (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe8db9f8a50>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1750752655169,
        "stop" : 1750752655169,
        "duration" : 0
      }
    }, {
      "uid" : "fa303416b1b276f9",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/fa303416b1b276f9",
      "status" : "passed",
      "time" : {
        "start" : 1750735588040,
        "stop" : 1750735588782,
        "duration" : 742
      }
    } ]
  },
  "2abe51877a7182eb4613bcd1006c2f64" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 0,
      "skipped" : 0,
      "passed" : 2,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "3560e6c9f0b596c3",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/3560e6c9f0b596c3",
      "status" : "passed",
      "time" : {
        "start" : 1750752670155,
        "stop" : 1750752670727,
        "duration" : 572
      }
    }, {
      "uid" : "f1c293cafbfcfcba",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/f1c293cafbfcfcba",
      "status" : "passed",
      "time" : {
        "start" : 1750735607523,
        "stop" : 1750735608087,
        "duration" : 564
      }
    } ]
  },
  "48bf13444dcd0c3d638f43c01750e463" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "f4e1a8f962d5b790",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/f4e1a8f962d5b790",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='frontend.niffler.dc', port=80): Max retries exceeded with url: /authorized?code=3AotFZI33KoDWPLmg19wOsxNRQPPVu_ebHst4OPCctlx4XkcIga6qLyNi6OTYLAT7B793yqxpJ8fEujXLue3QH2Qh4h3S1NWB3hzDveyJKCKLDXwRtbWKHf0SLIKof1g (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe8db9f8a50>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1750752654767,
        "stop" : 1750752654767,
        "duration" : 0
      }
    }, {
      "uid" : "8bb40c2afc106755",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/8bb40c2afc106755",
      "status" : "passed",
      "time" : {
        "start" : 1750735585365,
        "stop" : 1750735586144,
        "duration" : 779
      }
    } ]
  },
  "041bd4276295e6460af8da31fe50fa1a" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "6d95e2f33e3e34c0",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/6d95e2f33e3e34c0",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='frontend.niffler.dc', port=80): Max retries exceeded with url: /authorized?code=4oNXVbZDPy3rkhy0KIsRurQDzI9saIsESvNqGiQ7isna8NpKjuZQKgn49RZ8gHMov0eJfA1PWPeYM9q9BMBxi1WiVeivh4gjZYdZ209upA9IoDM6k7YbEiYEiNrQ3Mdy (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f22a8d34190>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1750752663404,
        "stop" : 1750752663405,
        "duration" : 1
      }
    }, {
      "uid" : "407d26558a238c46",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/407d26558a238c46",
      "status" : "passed",
      "time" : {
        "start" : 1750735602910,
        "stop" : 1750735602949,
        "duration" : 39
      }
    } ]
  },
  "ad6bfed8cf8d7686752550b2dcdee44d" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "63e243960ea8683d",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/63e243960ea8683d",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='frontend.niffler.dc', port=80): Max retries exceeded with url: /authorized?code=IKxl6aT1vru-4ckeYgtZCJ23atz7r7TJ03KuWA9PU5BYfuppu01oiq3k8k8c50ZEO3d7eRAvCKdaoi33ygG9LSAZIzJxRqB_VoJ-9CCOxXoCUsDdXcaHTSWz6G59QypH (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f96a8c08190>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1750752666343,
        "stop" : 1750752666343,
        "duration" : 0
      }
    }, {
      "uid" : "983868bff6525aa8",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/983868bff6525aa8",
      "status" : "passed",
      "time" : {
        "start" : 1750735604026,
        "stop" : 1750735604052,
        "duration" : 26
      }
    } ]
  },
  "28cbedaba6fbb0a465896bbd43a72d49" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "8c27e3b0a150c00",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/8c27e3b0a150c00",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='frontend.niffler.dc', port=80): Max retries exceeded with url: /authorized?code=3AotFZI33KoDWPLmg19wOsxNRQPPVu_ebHst4OPCctlx4XkcIga6qLyNi6OTYLAT7B793yqxpJ8fEujXLue3QH2Qh4h3S1NWB3hzDveyJKCKLDXwRtbWKHf0SLIKof1g (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe8db9f8a50>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1750752655300,
        "stop" : 1750752655300,
        "duration" : 0
      }
    }, {
      "uid" : "a537a5c77c707fd0",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/a537a5c77c707fd0",
      "status" : "passed",
      "time" : {
        "start" : 1750735588830,
        "stop" : 1750735590059,
        "duration" : 1229
      }
    } ]
  },
  "7881282ad3649379b956a17c8763b7d5" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "8fda5bd4aff46db3",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/8fda5bd4aff46db3",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=137.0.7151.103)\nStacktrace:\n#0 0x555c80270c9a <unknown>\n#1 0x555c7fd166e0 <unknown>\n#2 0x555c7fd0d7e7 <unknown>\n#3 0x555c7fcfe699 <unknown>\n#4 0x555c7fd003e0 <unknown>\n#5 0x555c7fcfea3d <unknown>\n#6 0x555c7fcfe3af <unknown>\n#7 0x555c7fcfe085 <unknown>\n#8 0x555c7fcfbeee <unknown>\n#9 0x555c7fcfc6ca <unknown>\n#10 0x555c7fd19c09 <unknown>\n#11 0x555c7fdb4ed5 <unknown>\n#12 0x555c7fd8de32 <unknown>\n#13 0x555c7fdb42cc <unknown>\n#14 0x555c7fd8dc03 <unknown>\n#15 0x555c7fd5a47b <unknown>\n#16 0x555c7fd5b0e1 <unknown>\n#17 0x555c8023544b <unknown>\n#18 0x555c8023937f <unknown>\n#19 0x555c8021cf89 <unknown>\n#20 0x555c80239f18 <unknown>\n#21 0x555c802016df <unknown>\n#22 0x555c8025e308 <unknown>\n#23 0x555c8025e4e6 <unknown>\n#24 0x555c8026fb76 <unknown>\n#25 0x7feac889caa4 <unknown>\n#26 0x7feac8929c3c <unknown>",
      "time" : {
        "start" : 1750752668937,
        "stop" : 1750752669193,
        "duration" : 256
      }
    }, {
      "uid" : "736a76f3567a0feb",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/736a76f3567a0feb",
      "status" : "passed",
      "time" : {
        "start" : 1750735604660,
        "stop" : 1750735605916,
        "duration" : 1256
      }
    } ]
  },
  "af2a2cda13c4b5f0d801632e3f4b98cf" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "cbc063aa005d14b3",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/cbc063aa005d14b3",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='frontend.niffler.dc', port=80): Max retries exceeded with url: /authorized?code=IKxl6aT1vru-4ckeYgtZCJ23atz7r7TJ03KuWA9PU5BYfuppu01oiq3k8k8c50ZEO3d7eRAvCKdaoi33ygG9LSAZIzJxRqB_VoJ-9CCOxXoCUsDdXcaHTSWz6G59QypH (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f96a8c08190>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1750752666696,
        "stop" : 1750752666696,
        "duration" : 0
      }
    }, {
      "uid" : "8a8c77ec20f37dc1",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/8a8c77ec20f37dc1",
      "status" : "passed",
      "time" : {
        "start" : 1750735604059,
        "stop" : 1750735604100,
        "duration" : 41
      }
    } ]
  },
  "d759dfae61b1528fa10c55b6ae86d2e5" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "e8538b8d87efbb15",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/e8538b8d87efbb15",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='frontend.niffler.dc', port=80): Max retries exceeded with url: /authorized?code=4oNXVbZDPy3rkhy0KIsRurQDzI9saIsESvNqGiQ7isna8NpKjuZQKgn49RZ8gHMov0eJfA1PWPeYM9q9BMBxi1WiVeivh4gjZYdZ209upA9IoDM6k7YbEiYEiNrQ3Mdy (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f22a8d34190>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1750752665084,
        "stop" : 1750752665084,
        "duration" : 0
      }
    }, {
      "uid" : "15a0de0ca905ba8c",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/15a0de0ca905ba8c",
      "status" : "passed",
      "time" : {
        "start" : 1750735603398,
        "stop" : 1750735603426,
        "duration" : 28
      }
    } ]
  },
  "aa974f277a45ddbbe71a441c3cf3f886" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "d2b6409644674362",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/d2b6409644674362",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='frontend.niffler.dc', port=80): Max retries exceeded with url: /authorized?code=3AotFZI33KoDWPLmg19wOsxNRQPPVu_ebHst4OPCctlx4XkcIga6qLyNi6OTYLAT7B793yqxpJ8fEujXLue3QH2Qh4h3S1NWB3hzDveyJKCKLDXwRtbWKHf0SLIKof1g (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe8db9f8a50>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1750752653367,
        "stop" : 1750752653367,
        "duration" : 0
      }
    }, {
      "uid" : "4739c2069e5646ce",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/4739c2069e5646ce",
      "status" : "passed",
      "time" : {
        "start" : 1750735574792,
        "stop" : 1750735576694,
        "duration" : 1902
      }
    } ]
  },
  "956dea3a79416c4d334b153b81fd12db" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "8a0f9ec3a58d4d93",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/8a0f9ec3a58d4d93",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=137.0.7151.103)\nStacktrace:\n#0 0x560f950b1c9a <unknown>\n#1 0x560f94b576e0 <unknown>\n#2 0x560f94b4e7e7 <unknown>\n#3 0x560f94b3f699 <unknown>\n#4 0x560f94b413e0 <unknown>\n#5 0x560f94b3fa3d <unknown>\n#6 0x560f94b3f3af <unknown>\n#7 0x560f94b3f085 <unknown>\n#8 0x560f94b3ceee <unknown>\n#9 0x560f94b3d6ca <unknown>\n#10 0x560f94b5ac09 <unknown>\n#11 0x560f94bf5ed5 <unknown>\n#12 0x560f94bcee32 <unknown>\n#13 0x560f94bf52cc <unknown>\n#14 0x560f94bcec03 <unknown>\n#15 0x560f94b9b47b <unknown>\n#16 0x560f94b9c0e1 <unknown>\n#17 0x560f9507644b <unknown>\n#18 0x560f9507a37f <unknown>\n#19 0x560f9505df89 <unknown>\n#20 0x560f9507af18 <unknown>\n#21 0x560f950426df <unknown>\n#22 0x560f9509f308 <unknown>\n#23 0x560f9509f4e6 <unknown>\n#24 0x560f950b0b76 <unknown>\n#25 0x7f009da9caa4 <unknown>\n#26 0x7f009db29c3c <unknown>",
      "time" : {
        "start" : 1750752653333,
        "stop" : 1750752653333,
        "duration" : 0
      }
    }, {
      "uid" : "3253250d94ce5db3",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/3253250d94ce5db3",
      "status" : "passed",
      "time" : {
        "start" : 1750735573462,
        "stop" : 1750735574763,
        "duration" : 1301
      }
    } ]
  },
  "9d2bb142289798857a779d08402df25e" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 0,
      "skipped" : 0,
      "passed" : 2,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "94c505148cbfd9b9",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/94c505148cbfd9b9",
      "status" : "passed",
      "time" : {
        "start" : 1750752664302,
        "stop" : 1750752665951,
        "duration" : 1649
      }
    }, {
      "uid" : "748a5b00eb8e074d",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/748a5b00eb8e074d",
      "status" : "passed",
      "time" : {
        "start" : 1750735602910,
        "stop" : 1750735603803,
        "duration" : 893
      }
    } ]
  },
  "1d31d40492e21034f51486703a2b3d1a" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "dd90d9d27a9c9052",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/dd90d9d27a9c9052",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='frontend.niffler.dc', port=80): Max retries exceeded with url: /authorized?code=3AotFZI33KoDWPLmg19wOsxNRQPPVu_ebHst4OPCctlx4XkcIga6qLyNi6OTYLAT7B793yqxpJ8fEujXLue3QH2Qh4h3S1NWB3hzDveyJKCKLDXwRtbWKHf0SLIKof1g (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe8db9f8a50>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1750752654898,
        "stop" : 1750752654898,
        "duration" : 0
      }
    }, {
      "uid" : "6f445434f105f230",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/6f445434f105f230",
      "status" : "passed",
      "time" : {
        "start" : 1750735586146,
        "stop" : 1750735586911,
        "duration" : 765
      }
    } ]
  },
  "cdf98741ede9b0c8595f8d04bddc2c50" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "edfc552040ec9a41",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/edfc552040ec9a41",
      "status" : "broken",
      "statusDetails" : "sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation \"user\" does not exist\nLINE 2: FROM \"user\" \n             ^\n\n[SQL: SELECT \"user\".id, \"user\".username, \"user\".currency, \"user\".firstname, \"user\".surname, \"user\".photo, \"user\".photo_small, \"user\".full_name \nFROM \"user\" \nWHERE \"user\".username = %(username_1)s]\n[parameters: {'username_1': 'Patricia Holmes'}]\n(Background on this error at: https://sqlalche.me/e/20/f405)",
      "time" : {
        "start" : 1750752666834,
        "stop" : 1750752667251,
        "duration" : 417
      }
    }, {
      "uid" : "ddef297db05c696",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/ddef297db05c696",
      "status" : "passed",
      "time" : {
        "start" : 1750735605046,
        "stop" : 1750735605602,
        "duration" : 556
      }
    } ]
  },
  "3fe08d77751f5f4a34b6541896c8e78f" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "1afb53d4ee036cb7",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/1afb53d4ee036cb7",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='frontend.niffler.dc', port=80): Max retries exceeded with url: /authorized?code=IKxl6aT1vru-4ckeYgtZCJ23atz7r7TJ03KuWA9PU5BYfuppu01oiq3k8k8c50ZEO3d7eRAvCKdaoi33ygG9LSAZIzJxRqB_VoJ-9CCOxXoCUsDdXcaHTSWz6G59QypH (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f96a8c08190>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1750752665361,
        "stop" : 1750752665361,
        "duration" : 0
      }
    }, {
      "uid" : "de88e320585936a2",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/de88e320585936a2",
      "status" : "passed",
      "time" : {
        "start" : 1750735603774,
        "stop" : 1750735603813,
        "duration" : 39
      }
    } ]
  },
  "b58d3754629b6649908d864df3871b40" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "7c5fd3f82c7347a2",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/7c5fd3f82c7347a2",
      "status" : "broken",
      "statusDetails" : "sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation \"user\" does not exist\nLINE 2: FROM \"user\" \n             ^\n\n[SQL: SELECT \"user\".id, \"user\".username, \"user\".currency, \"user\".firstname, \"user\".surname, \"user\".photo, \"user\".photo_small, \"user\".full_name \nFROM \"user\" \nWHERE \"user\".username = %(username_1)s]\n[parameters: {'username_1': 'Ronnie Hernandez'}]\n(Background on this error at: https://sqlalche.me/e/20/f405)",
      "time" : {
        "start" : 1750752666983,
        "stop" : 1750752667217,
        "duration" : 234
      }
    }, {
      "uid" : "5868ee687c058c12",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/5868ee687c058c12",
      "status" : "passed",
      "time" : {
        "start" : 1750735604255,
        "stop" : 1750735604578,
        "duration" : 323
      }
    } ]
  },
  "3469912857c472d5c87509a33c7cf1b0" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "ea618be64d04c93d",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/ea618be64d04c93d",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='frontend.niffler.dc', port=80): Max retries exceeded with url: /authorized?code=4oNXVbZDPy3rkhy0KIsRurQDzI9saIsESvNqGiQ7isna8NpKjuZQKgn49RZ8gHMov0eJfA1PWPeYM9q9BMBxi1WiVeivh4gjZYdZ209upA9IoDM6k7YbEiYEiNrQ3Mdy (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f22a8d34190>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1750752665363,
        "stop" : 1750752665363,
        "duration" : 0
      }
    }, {
      "uid" : "194d45638d5e99fc",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/194d45638d5e99fc",
      "status" : "passed",
      "time" : {
        "start" : 1750735603475,
        "stop" : 1750735603494,
        "duration" : 19
      }
    } ]
  },
  "6fc6ae7dde764904e12ab00082c84705" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "207f160a5674e937",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/207f160a5674e937",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=137.0.7151.103)\nStacktrace:\n#0 0x5615ab831c9a <unknown>\n#1 0x5615ab2d76e0 <unknown>\n#2 0x5615ab2ce7e7 <unknown>\n#3 0x5615ab2bf699 <unknown>\n#4 0x5615ab2c13e0 <unknown>\n#5 0x5615ab2bfa3d <unknown>\n#6 0x5615ab2bf3af <unknown>\n#7 0x5615ab2bf085 <unknown>\n#8 0x5615ab2bceee <unknown>\n#9 0x5615ab2bd6ca <unknown>\n#10 0x5615ab2dac09 <unknown>\n#11 0x5615ab375ed5 <unknown>\n#12 0x5615ab34ee32 <unknown>\n#13 0x5615ab3752cc <unknown>\n#14 0x5615ab34ec03 <unknown>\n#15 0x5615ab31b47b <unknown>\n#16 0x5615ab31c0e1 <unknown>\n#17 0x5615ab7f644b <unknown>\n#18 0x5615ab7fa37f <unknown>\n#19 0x5615ab7ddf89 <unknown>\n#20 0x5615ab7faf18 <unknown>\n#21 0x5615ab7c26df <unknown>\n#22 0x5615ab81f308 <unknown>\n#23 0x5615ab81f4e6 <unknown>\n#24 0x5615ab830b76 <unknown>\n#25 0x7f855e29caa4 <unknown>\n#26 0x7f855e329c3c <unknown>",
      "time" : {
        "start" : 1750752665082,
        "stop" : 1750752665220,
        "duration" : 138
      }
    }, {
      "uid" : "42ae1aed17ee1e85",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/42ae1aed17ee1e85",
      "status" : "passed",
      "time" : {
        "start" : 1750735605039,
        "stop" : 1750735607983,
        "duration" : 2944
      }
    } ]
  },
  "6235bcec76b267f6626797fea03a579c" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "3f8230904d2b217a",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/3f8230904d2b217a",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='frontend.niffler.dc', port=80): Max retries exceeded with url: /authorized?code=3AotFZI33KoDWPLmg19wOsxNRQPPVu_ebHst4OPCctlx4XkcIga6qLyNi6OTYLAT7B793yqxpJ8fEujXLue3QH2Qh4h3S1NWB3hzDveyJKCKLDXwRtbWKHf0SLIKof1g (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe8db9f8a50>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1750752655444,
        "stop" : 1750752655444,
        "duration" : 0
      }
    }, {
      "uid" : "a367c65cf4ab188d",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/a367c65cf4ab188d",
      "status" : "passed",
      "time" : {
        "start" : 1750735590108,
        "stop" : 1750735592538,
        "duration" : 2430
      }
    } ]
  },
  "cd841d96460c2483f99e75e82349843b" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "799a2145c6b530f",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/799a2145c6b530f",
      "status" : "broken",
      "statusDetails" : "sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation \"user\" does not exist\nLINE 2: FROM \"user\" \n             ^\n\n[SQL: SELECT \"user\".id, \"user\".username, \"user\".currency, \"user\".firstname, \"user\".surname, \"user\".photo, \"user\".photo_small, \"user\".full_name \nFROM \"user\" \nWHERE \"user\".username = %(username_1)s]\n[parameters: {'username_1': 'Ashley Perry'}]\n(Background on this error at: https://sqlalche.me/e/20/f405)",
      "time" : {
        "start" : 1750752668030,
        "stop" : 1750752668335,
        "duration" : 305
      }
    }, {
      "uid" : "6a9c42a5095eed74",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/6a9c42a5095eed74",
      "status" : "passed",
      "time" : {
        "start" : 1750735604593,
        "stop" : 1750735605041,
        "duration" : 448
      }
    } ]
  },
  "db6773b6af3b09698fee8cef1ac01d02" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "f689ae77cf58604c",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/f689ae77cf58604c",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='frontend.niffler.dc', port=80): Max retries exceeded with url: /authorized?code=IKxl6aT1vru-4ckeYgtZCJ23atz7r7TJ03KuWA9PU5BYfuppu01oiq3k8k8c50ZEO3d7eRAvCKdaoi33ygG9LSAZIzJxRqB_VoJ-9CCOxXoCUsDdXcaHTSWz6G59QypH (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f96a8c08190>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1750752665108,
        "stop" : 1750752665108,
        "duration" : 0
      }
    }, {
      "uid" : "2d773d3ba484ab27",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/2d773d3ba484ab27",
      "status" : "passed",
      "time" : {
        "start" : 1750735603623,
        "stop" : 1750735603699,
        "duration" : 76
      }
    } ]
  },
  "38f8009d7be4d8e20d113bf314c7b53f" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "a0c95083a2ad09fa",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/a0c95083a2ad09fa",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=137.0.7151.103)\nStacktrace:\n#0 0x560f950b1c9a <unknown>\n#1 0x560f94b576e0 <unknown>\n#2 0x560f94b4e7e7 <unknown>\n#3 0x560f94b3f699 <unknown>\n#4 0x560f94b413e0 <unknown>\n#5 0x560f94b3fa3d <unknown>\n#6 0x560f94b3f3af <unknown>\n#7 0x560f94b3f085 <unknown>\n#8 0x560f94b3ceee <unknown>\n#9 0x560f94b3d6ca <unknown>\n#10 0x560f94b5ac09 <unknown>\n#11 0x560f94bf5ed5 <unknown>\n#12 0x560f94bcee32 <unknown>\n#13 0x560f94bf52cc <unknown>\n#14 0x560f94bcec03 <unknown>\n#15 0x560f94b9b47b <unknown>\n#16 0x560f94b9c0e1 <unknown>\n#17 0x560f9507644b <unknown>\n#18 0x560f9507a37f <unknown>\n#19 0x560f9505df89 <unknown>\n#20 0x560f9507af18 <unknown>\n#21 0x560f950426df <unknown>\n#22 0x560f9509f308 <unknown>\n#23 0x560f9509f4e6 <unknown>\n#24 0x560f950b0b76 <unknown>\n#25 0x7f009da9caa4 <unknown>\n#26 0x7f009db29c3c <unknown>",
      "time" : {
        "start" : 1750752654475,
        "stop" : 1750752654475,
        "duration" : 0
      }
    }, {
      "uid" : "110c9af0b8b8cd0e",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/110c9af0b8b8cd0e",
      "status" : "passed",
      "time" : {
        "start" : 1750735582752,
        "stop" : 1750735583719,
        "duration" : 967
      }
    } ]
  },
  "02d302d044b634d2b432e25f90b38921" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "2a5826a0416ed291",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/2a5826a0416ed291",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='frontend.niffler.dc', port=80): Max retries exceeded with url: /authorized?code=3AotFZI33KoDWPLmg19wOsxNRQPPVu_ebHst4OPCctlx4XkcIga6qLyNi6OTYLAT7B793yqxpJ8fEujXLue3QH2Qh4h3S1NWB3hzDveyJKCKLDXwRtbWKHf0SLIKof1g (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe8db9f8a50>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1750752655028,
        "stop" : 1750752655028,
        "duration" : 0
      }
    }, {
      "uid" : "5f404bf3672dea6f",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/5f404bf3672dea6f",
      "status" : "passed",
      "time" : {
        "start" : 1750735587249,
        "stop" : 1750735588003,
        "duration" : 754
      }
    } ]
  },
  "175036bced3eb37a54df21fb42225191" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "317141bcb013ed96",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/317141bcb013ed96",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='frontend.niffler.dc', port=80): Max retries exceeded with url: /authorized?code=4oNXVbZDPy3rkhy0KIsRurQDzI9saIsESvNqGiQ7isna8NpKjuZQKgn49RZ8gHMov0eJfA1PWPeYM9q9BMBxi1WiVeivh4gjZYdZ209upA9IoDM6k7YbEiYEiNrQ3Mdy (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f22a8d34190>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1750752664315,
        "stop" : 1750752664315,
        "duration" : 0
      }
    }, {
      "uid" : "2145f05b132ad753",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/2145f05b132ad753",
      "status" : "passed",
      "time" : {
        "start" : 1750735603118,
        "stop" : 1750735603142,
        "duration" : 24
      }
    } ]
  },
  "6a8d6b0af8c1dd48f23b7649521d0530" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "cd5cc6b152d3fb53",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/cd5cc6b152d3fb53",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='frontend.niffler.dc', port=80): Max retries exceeded with url: /authorized?code=IKxl6aT1vru-4ckeYgtZCJ23atz7r7TJ03KuWA9PU5BYfuppu01oiq3k8k8c50ZEO3d7eRAvCKdaoi33ygG9LSAZIzJxRqB_VoJ-9CCOxXoCUsDdXcaHTSWz6G59QypH (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f96a8c08190>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1750752665991,
        "stop" : 1750752665991,
        "duration" : 0
      }
    }, {
      "uid" : "2a9942f09141ccbe",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/2a9942f09141ccbe",
      "status" : "passed",
      "time" : {
        "start" : 1750735604004,
        "stop" : 1750735604022,
        "duration" : 18
      }
    } ]
  },
  "adeef0ae45b52d2a032d764073066d5b" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "fc97cc7a9e16ae12",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/fc97cc7a9e16ae12",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=137.0.7151.103)\nStacktrace:\n#0 0x560f950b1c9a <unknown>\n#1 0x560f94b576e0 <unknown>\n#2 0x560f94b4e7e7 <unknown>\n#3 0x560f94b3f699 <unknown>\n#4 0x560f94b413e0 <unknown>\n#5 0x560f94b3fa3d <unknown>\n#6 0x560f94b3f3af <unknown>\n#7 0x560f94b3f085 <unknown>\n#8 0x560f94b3ceee <unknown>\n#9 0x560f94b3d6ca <unknown>\n#10 0x560f94b5ac09 <unknown>\n#11 0x560f94bf5ed5 <unknown>\n#12 0x560f94bcee32 <unknown>\n#13 0x560f94bf52cc <unknown>\n#14 0x560f94bcec03 <unknown>\n#15 0x560f94b9b47b <unknown>\n#16 0x560f94b9c0e1 <unknown>\n#17 0x560f9507644b <unknown>\n#18 0x560f9507a37f <unknown>\n#19 0x560f9505df89 <unknown>\n#20 0x560f9507af18 <unknown>\n#21 0x560f950426df <unknown>\n#22 0x560f9509f308 <unknown>\n#23 0x560f9509f4e6 <unknown>\n#24 0x560f950b0b76 <unknown>\n#25 0x7f009da9caa4 <unknown>\n#26 0x7f009db29c3c <unknown>",
      "time" : {
        "start" : 1750752639891,
        "stop" : 1750752639891,
        "duration" : 0
      }
    }, {
      "uid" : "8d4c80fa725e2f17",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/8d4c80fa725e2f17",
      "status" : "passed",
      "time" : {
        "start" : 1750735566217,
        "stop" : 1750735566989,
        "duration" : 772
      }
    } ]
  },
  "3c910fd7d50d4933f7022fb141e4a0a6" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "4185a77481aca7d4",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/4185a77481aca7d4",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='frontend.niffler.dc', port=80): Max retries exceeded with url: /authorized?code=3AotFZI33KoDWPLmg19wOsxNRQPPVu_ebHst4OPCctlx4XkcIga6qLyNi6OTYLAT7B793yqxpJ8fEujXLue3QH2Qh4h3S1NWB3hzDveyJKCKLDXwRtbWKHf0SLIKof1g (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe8db9f8a50>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1750752654313,
        "stop" : 1750752654313,
        "duration" : 0
      }
    }, {
      "uid" : "b996a0072ebceb0e",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/b996a0072ebceb0e",
      "status" : "passed",
      "time" : {
        "start" : 1750735580818,
        "stop" : 1750735581774,
        "duration" : 956
      }
    } ]
  },
  "79663519f4e5204232f6c415d0dfa546" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "411378a2e8c49b6f",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/411378a2e8c49b6f",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='frontend.niffler.dc', port=80): Max retries exceeded with url: /authorized?code=3AotFZI33KoDWPLmg19wOsxNRQPPVu_ebHst4OPCctlx4XkcIga6qLyNi6OTYLAT7B793yqxpJ8fEujXLue3QH2Qh4h3S1NWB3hzDveyJKCKLDXwRtbWKHf0SLIKof1g (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe8db9f8a50>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1750752654635,
        "stop" : 1750752654635,
        "duration" : 0
      }
    }, {
      "uid" : "7f7d455129e3aa6b",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/7f7d455129e3aa6b",
      "status" : "passed",
      "time" : {
        "start" : 1750735584504,
        "stop" : 1750735585363,
        "duration" : 859
      }
    } ]
  },
  "edb1b82e6448a8a8147ac05df9be33ea" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "fca449c1802c8e30",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/fca449c1802c8e30",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8089): Max retries exceeded with url: /ws (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f002d3ee580>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1750752669105,
        "stop" : 1750752669547,
        "duration" : 442
      }
    }, {
      "uid" : "1a103f2beb2ddba7",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/1a103f2beb2ddba7",
      "status" : "passed",
      "time" : {
        "start" : 1750735604646,
        "stop" : 1750735605458,
        "duration" : 812
      }
    } ]
  },
  "8061981e1d41773ad3738412f5d81c2d" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "96df8b947c13f681",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/96df8b947c13f681",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='frontend.niffler.dc', port=80): Max retries exceeded with url: /authorized?code=4oNXVbZDPy3rkhy0KIsRurQDzI9saIsESvNqGiQ7isna8NpKjuZQKgn49RZ8gHMov0eJfA1PWPeYM9q9BMBxi1WiVeivh4gjZYdZ209upA9IoDM6k7YbEiYEiNrQ3Mdy (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f22a8d34190>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1750752665629,
        "stop" : 1750752665629,
        "duration" : 0
      }
    }, {
      "uid" : "c2c6a51aab8feae1",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/c2c6a51aab8feae1",
      "status" : "passed",
      "time" : {
        "start" : 1750735603547,
        "stop" : 1750735603547,
        "duration" : 0
      }
    } ]
  },
  "ef09ea4a3aa17250972d2103d767aeb9" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "1b33c3bd098641b",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/1b33c3bd098641b",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='frontend.niffler.dc', port=80): Max retries exceeded with url: /authorized?code=3AotFZI33KoDWPLmg19wOsxNRQPPVu_ebHst4OPCctlx4XkcIga6qLyNi6OTYLAT7B793yqxpJ8fEujXLue3QH2Qh4h3S1NWB3hzDveyJKCKLDXwRtbWKHf0SLIKof1g (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe8db9f8a50>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1750752655833,
        "stop" : 1750752655833,
        "duration" : 0
      }
    }, {
      "uid" : "f042437cbbede8a2",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/f042437cbbede8a2",
      "status" : "passed",
      "time" : {
        "start" : 1750735595432,
        "stop" : 1750735595434,
        "duration" : 2
      }
    } ]
  },
  "d62dc29379749a47216c4569e7204210" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "a7c99c8daf878e02",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/a7c99c8daf878e02",
      "status" : "broken",
      "statusDetails" : "sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation \"user\" does not exist\nLINE 2: FROM \"user\" \n             ^\n\n[SQL: SELECT \"user\".id, \"user\".username, \"user\".currency, \"user\".firstname, \"user\".surname, \"user\".photo, \"user\".photo_small, \"user\".full_name \nFROM \"user\" \nWHERE \"user\".username = %(username_1)s]\n[parameters: {'username_1': 'daycassandra'}]\n(Background on this error at: https://sqlalche.me/e/20/f405)",
      "time" : {
        "start" : 1750752656465,
        "stop" : 1750752657233,
        "duration" : 768
      }
    }, {
      "uid" : "b3f15fad54fd5b39",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/b3f15fad54fd5b39",
      "status" : "passed",
      "time" : {
        "start" : 1750735595780,
        "stop" : 1750735596624,
        "duration" : 844
      }
    } ]
  },
  "a42991aca7d1494e84fb0dba166660b4" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "fa4184d8ef91f180",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/fa4184d8ef91f180",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=137.0.7151.103)\nStacktrace:\n#0 0x555c80270c9a <unknown>\n#1 0x555c7fd166e0 <unknown>\n#2 0x555c7fd0d7e7 <unknown>\n#3 0x555c7fcfe699 <unknown>\n#4 0x555c7fd003e0 <unknown>\n#5 0x555c7fcfea3d <unknown>\n#6 0x555c7fcfe3af <unknown>\n#7 0x555c7fcfe085 <unknown>\n#8 0x555c7fcfbeee <unknown>\n#9 0x555c7fcfc6ca <unknown>\n#10 0x555c7fd19c09 <unknown>\n#11 0x555c7fdb4ed5 <unknown>\n#12 0x555c7fd8de32 <unknown>\n#13 0x555c7fdb42cc <unknown>\n#14 0x555c7fd8dc03 <unknown>\n#15 0x555c7fd5a47b <unknown>\n#16 0x555c7fd5b0e1 <unknown>\n#17 0x555c8023544b <unknown>\n#18 0x555c8023937f <unknown>\n#19 0x555c8021cf89 <unknown>\n#20 0x555c80239f18 <unknown>\n#21 0x555c802016df <unknown>\n#22 0x555c8025e308 <unknown>\n#23 0x555c8025e4e6 <unknown>\n#24 0x555c8026fb76 <unknown>\n#25 0x7feac889caa4 <unknown>\n#26 0x7feac8929c3c <unknown>",
      "time" : {
        "start" : 1750752668645,
        "stop" : 1750752668872,
        "duration" : 227
      }
    }, {
      "uid" : "8da5f5ea29d04730",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/8da5f5ea29d04730",
      "status" : "passed",
      "time" : {
        "start" : 1750735607064,
        "stop" : 1750735607679,
        "duration" : 615
      }
    } ]
  },
  "abb227afeb648663cd347fd02196aa22" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 0,
      "skipped" : 0,
      "passed" : 2,
      "unknown" : 0,
      "total" : 2
    },
    "items" : [ {
      "uid" : "c9d20ff00ca7aa75",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/43/#testresult/c9d20ff00ca7aa75",
      "status" : "passed",
      "time" : {
        "start" : 1750752668912,
        "stop" : 1750752669686,
        "duration" : 774
      }
    }, {
      "uid" : "24842b3caa054b77",
      "reportUrl" : "https://shade1471.github.io/niffler-py-st3/42/#testresult/24842b3caa054b77",
      "status" : "passed",
      "time" : {
        "start" : 1750735606484,
        "stop" : 1750735607519,
        "duration" : 1035
      }
    } ]
  }
}